import { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    slug: 'grabit',
    title: 'Grabit',
    subtitle: 'Hyperlocal Deal Discovery App',
    role: 'React Native Developer',
    timeframe: '2024',
    highlights: [
      'Hyperlocal deal discovery app offering real-time offers within a 5km radius',
      'Designed QR-based offer system, increasing engagement by 25%',
      'Implemented in-app analytics to track coupon views and redemptions for actionable insights',
    ],
    features: [
      'QR code-based offer redemption',
      'Real-time location-based deals within 5km radius',
      'In-app analytics dashboard',
      'Push notification campaigns',
      'Coupon tracking and redemption insights',
    ],
    stack: ['JavaScript', 'TypeScript', 'React Native', 'Redux', 'REST APIs', 'Firebase', 'AWS CLI', 'Google Maps API', 'Payment Gateways'],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.corenettech.grabituser&hl=en_IN&pli=1',
      appStore: 'https://apps.apple.com/in/app/grabituser/id6480311561',
    },
    coverImage: '/images/projects/grabit.png',
    gallery: ['/images/projects/grabit-1.png', '/images/projects/grabit-2.png'],
    impact: {
      mauDelta: 0.25,
      rating: 4.9,
      installs: '1K+',
    },
    category: 'mobile',
  },
  {
    slug: 'grabit-business',
    title: 'Grabit Business',
    subtitle: 'Merchant Platform for Geo-targeted Campaigns',
    role: 'React Native Developer',
    timeframe: '2023 - 2024',
    highlights: [
      'Merchant platform for geo-targeted campaigns using coins and push/SMS notifications',
      'Built campaign engine used by 1,000+ businesses',
      'Created dashboards for redemption tracking, improving marketing ROI',
    ],
    features: [
      'Campaign creation and management',
      'Geo-targeted marketing campaigns',
      'Real-time redemption tracking',
      'Push and SMS notifications',
      'Business analytics dashboard',
    ],
    stack: ['JavaScript', 'TypeScript', 'React Native', 'Redux', 'REST APIs', 'Firebase', 'AWS CLI'],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.corenettech.grabitbusiness',
      appStore: 'https://apps.apple.com/in/app/grabit-business-app/id6484402238',
    },
    coverImage: '/images/projects/grabit-business.png',
    gallery: ['/images/projects/grabit-business-1.png'],
    impact: {
      installs: '1K+',
      rating: 4.3,
    },
    category: 'mobile',
  },
  {
    slug: 'hariprabodham-vrund',
    title: 'Hariprabodham Vrund',
    subtitle: 'Devotional Streaming App',
    role: 'React Native Developer',
    timeframe: '2022 - 2023',
    highlights: [
      'Devotional streaming app with offline playback, playlists, and personalized feeds',
      'Achieved 4.9+ Play Store rating and increased retention rates',
      'Implemented offline audio streaming and personalized content system',
    ],
    features: [
      'Offline audio streaming',
      'Custom playlists',
      'Personalized content feeds',
      'Background playback',
      'High user retention features',
    ],
    stack: ['React Native', 'Zustand', 'Firebase', 'REST APIs', 'TypeScript'],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.suhradvrund&hl=en_IN',
      appStore: 'https://apps.apple.com/in/app/hariprabodham-vrund/id6474902923',
    },
    coverImage: '/images/projects/hariprabodham.png',
    gallery: ['/images/projects/hariprabodham-1.png'],
    impact: {
      rating: 4.9,
      installs: '10K+',
    },
    category: 'mobile',
  },
  {
    slug: 'krisiyukta',
    title: 'Krisiyukta',
    subtitle: 'Agri-tech App for Farmers',
    role: 'React Native Developer',
    timeframe: '2022 - 2023',
    highlights: [
      'Agri-tech app for farmers with weather data, market prices, and community features',
      'Built offline-first multilingual UI and integrated live data APIs',
      'Created comprehensive farmer community and resource platform',
    ],
    features: [
      'Weather forecasts and alerts',
      'Market price tracking',
      'Community features',
      'Multilingual support',
      'Offline-first architecture',
    ],
    stack: ['React Native', 'REST APIs', 'Firebase', 'Expo',],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.krisiyukta.www&hl=en_IN',
    },
    coverImage: '/images/projects/krisiyukta.png',
    gallery: ['/images/projects/krisiyukta-1.png'],
    impact: {
      rating: 4.5,
      installs: '1K+',
    },
    category: 'mobile',
  },
  {
    slug: 'wardrobe-app',
    title: 'Wardrobe App',
    subtitle: 'Smart Outfit Management',
    role: 'React Native Developer',
    timeframe: '2023',
    highlights: [
      'Smart outfit management app with drag-and-drop calendar and tagging system',
      'Implemented intuitive drag-drop interface for outfit planning',
      'Built comprehensive clothing categorization and organization system',
    ],
    features: [
      'Drag-drop calendar planning',
      'Clothing categorization and tagging',
      'Outfit planning system',
      'Smart organization features',
      'Intuitive user interface',
    ],
    stack: ['React Native', 'TypeScript', 'REST APIs'],
    links: {},
    coverImage: '/images/projects/wardrobe.png',
    gallery: ['/images/projects/wardrobe-1.png'],
    impact: {},
    category: 'mobile',
  },
  {
    slug: 'akshar-yatra',
    title: 'Akshar Yatra',
    subtitle: 'Event Management App',
    role: 'React Native Developer',
    timeframe: '2023',
    highlights: [
      'Event management app with offline check-in and attendance tracking',
      'Built for spiritual gatherings, reducing manual work significantly',
      'Implemented offline-first architecture for reliable event management',
    ],
    features: [
      'Offline check-in system',
      'Attendance tracking',
      'Event management tools',
      'Spiritual gathering features',
      'Manual work reduction',
    ],
    stack: ['React Native', 'Firebase', 'Offline Storage'],
    links: {},
    coverImage: '/images/projects/akshar-yatra.png',
    gallery: ['/images/projects/akshar-yatra-1.png'],
    impact: {},
    category: 'mobile',
  },
  {
    slug: 'eremotehire',
    title: 'eRemotehire',
    subtitle: 'AI-Powered Hiring Platform',
    role: 'Full-Stack Developer',
    timeframe: '2023 - 2024',
    highlights: [
      'AI-powered hiring platform with dashboards, resume parsing, and job matching logic',
      'Enhanced UI responsiveness and reduced load times significantly',
      'Built comprehensive recruitment and candidate management system',
    ],
    features: [
      'AI-powered job matching',
      'Resume parsing system',
      'Recruitment dashboards',
      'Candidate management',
      'Performance optimizations',
    ],
    stack: ['React.js', 'Next.js', 'TypeScript', 'REST APIs', ],
    links: {},
    coverImage: '/images/projects/eremotehire.png',
    gallery: ['/images/projects/eremotehire-1.png'],
    impact: {},
    category: 'web',
  },
  {
    slug: 'optox',
    title: 'OptoX',
    subtitle: 'Blockchain P2P Crypto Platform',
    role: 'Blockchain Developer',
    timeframe: '2024',
    highlights: [
      'Blockchain-based P2P crypto transaction platform with wallet authentication',
      'Implemented secure real-time trading interface',
      'Built comprehensive Web3 wallet integration system',
    ],
    features: [
      'P2P crypto transactions',
      'Wallet authentication',
      'Real-time trading interface',
      'Blockchain integration',
      'Secure transaction system',
    ],
    stack: ['React.js', 'Next.js', 'REST APIs', 'Blockchain', 'Web3', 'TypeScript'],
    links: {},
    coverImage: '/images/projects/optox.png',
    gallery: ['/images/projects/optox-1.png'],
    impact: {},
    category: 'blockchain',
  },
];