import { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    slug: 'grabit',
    title: 'Grabit',
    subtitle: 'Hyperlocal Deal Discovery App',
    role: 'Lead React Native Developer',
    timeframe: '2023 - 2024',
    highlights: [
      'Designed QR-based offer system that increased engagement by 25%',
      'Built in-app analytics for coupon views and redemptions',
      'Implemented 5km radius geo-targeting for deals',
    ],
    features: [
      'QR code-based offer redemption',
      'Real-time location-based deals',
      'In-app analytics dashboard',
      'Push notification campaigns',
      'Social sharing integration',
    ],
    stack: ['React Native', 'TypeScript', 'Redux', 'Firebase', 'Google Maps API', 'Payments'],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.grabit',
      appStore: 'https://apps.apple.com/app/grabit/id123456789',
    },
    coverImage: '/images/projects/grabit.png',
    gallery: ['/images/projects/grabit-1.png', '/images/projects/grabit-2.png'],
    impact: {
      mauDelta: 0.25,
      rating: 4.5,
      installs: '10K+',
    },
    category: 'mobile',
  },
  {
    slug: 'grabit-business',
    title: 'Grabit Business',
    subtitle: 'Merchant Platform for Geo-targeted Campaigns',
    role: 'Full-Stack Developer',
    timeframe: '2023 - 2024',
    highlights: [
      'Built campaign engine used by 1,000+ businesses',
      'Developed dashboards for redemption tracking',
      'Improved marketing ROI through better analytics',
    ],
    features: [
      'Campaign creation and management',
      'Real-time redemption tracking',
      'Geographic targeting tools',
      'Revenue analytics dashboard',
      'Merchant notification system',
    ],
    stack: ['React Native', 'TypeScript', 'Expo', 'Firebase', 'AWS CLI'],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.grabit.business',
      appStore: 'https://apps.apple.com/app/grabit-business/id123456789',
    },
    coverImage: '/images/projects/grabit-business.png',
    gallery: ['/images/projects/grabit-business-1.png'],
    impact: {
      installs: '1K+',
      rating: 4.3,
    },
    category: 'mobile',
  },
  {
    slug: 'hariprabodham-vrund',
    title: 'Hariprabodham Vrund',
    subtitle: 'Devotional Streaming with Offline Support',
    role: 'Mobile Developer',
    timeframe: '2022 - 2023',
    highlights: [
      'Achieved 4.9+ Play Store rating with high retention',
      'Implemented offline audio streaming',
      'Built personalized content recommendation system',
    ],
    features: [
      'Offline audio streaming',
      'Custom playlists',
      'Personalized content feeds',
      'Background playback',
      'Social features and sharing',
    ],
    stack: ['React Native', 'Redux', 'Firebase'],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.hariprabodham',
      appStore: 'https://apps.apple.com/app/hariprabodham-vrund/id123456789',
    },
    coverImage: '/images/projects/hariprabodham.png',
    gallery: ['/images/projects/hariprabodham-1.png'],
    impact: {
      rating: 4.9,
      installs: '50K+',
    },
    category: 'mobile',
  },
  {
    slug: 'krisiyukta',
    title: 'Krisiyukta',
    subtitle: 'Agri-tech App for Farmers',
    role: 'React Native Developer',
    timeframe: '2022 - 2023',
    highlights: [
      'Built offline-first multilingual UI',
      'Integrated live weather and market price APIs',
      'Created farmer community features',
    ],
    features: [
      'Weather forecasts and alerts',
      'Market price tracking',
      'Crop management tools',
      'Farmer community chat',
      'Multilingual support',
    ],
    stack: ['React Native', 'REST APIs', 'SQLite'],
    links: {
      playStore: 'https://play.google.com/store/apps/details?id=com.krisiyukta',
    },
    coverImage: '/images/projects/krisiyukta.png',
    gallery: ['/images/projects/krisiyukta-1.png'],
    impact: {
      rating: 4.2,
      installs: '25K+',
    },
    category: 'mobile',
  },
  {
    slug: 'wardrobe-app',
    title: 'Wardrobe App',
    subtitle: 'Smart Outfit Planning',
    role: 'UI/UX Developer',
    timeframe: '2023',
    highlights: [
      'Implemented drag-drop calendar interface',
      'Built clothing categorization system',
      'Created outfit recommendation engine',
    ],
    features: [
      'Drag-drop calendar planning',
      'Clothing categorization and tagging',
      'Outfit recommendations',
      'Weather-based suggestions',
      'Photo-based wardrobe cataloging',
    ],
    stack: ['React Native', 'TypeScript', 'Reanimated'],
    links: {},
    coverImage: '/images/projects/wardrobe.png',
    gallery: ['/images/projects/wardrobe-1.png'],
    impact: {},
    category: 'mobile',
  },
  {
    slug: 'optox',
    title: 'OptoX',
    subtitle: 'Blockchain P2P Crypto Wallet',
    role: 'Blockchain Developer',
    timeframe: '2024',
    highlights: [
      'Implemented secure real-time trading',
      'Built Web3 wallet integration',
      'Created P2P transaction system',
    ],
    features: [
      'Secure wallet management',
      'Real-time crypto trading',
      'P2P transactions',
      'Portfolio tracking',
      'Multi-chain support',
    ],
    stack: ['React Native', 'Web3', 'Blockchain', 'TypeScript'],
    links: {},
    coverImage: '/images/projects/optox.png',
    gallery: ['/images/projects/optox-1.png'],
    impact: {},
    category: 'blockchain',
  },
];